[build]
builder = "NIXPACKS"
buildCommand = "pip install -r requirements.txt"

[deploy]
startCommand = "gunicorn app:app"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[phases.setup]
cmds = ["apt-get update", "apt-get install -y build-essential"]

[phases.build]
cmds = ["pip install --upgrade pip", "pip install -r requirements.txt"]

[phases.cleanup]
cmds = ["apt-get clean", "rm -rf /var/lib/apt/lists/*"]

[env]
PYTHONUNBUFFERED = "1"
RAILWAY_ENVIRONMENT = "production"